os: linux
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y cpanminus libperl-dev perl
    - sudo cpanm Template Test::TrailingSpace
    - gem install sass compass compass-blueprint
script: "m() { make \"$@\" ; } ; cd vim-begin/tt2-source/ && ./gen-helpers && m && m test"
