cache:
    directories:
        - $HOME/perl_modules
        - $HOME/tidyall_d
os: linux
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get --no-install-recommends install -y cpanminus libhunspell-dev libperl-dev perl python3 python3-setuptools python3-pip
    - eval "$(GIMME_GO_VERSION=1.11 gimme)"
    - go get -u github.com/tdewolff/minify/cmd/minify
    - eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
    - cpanm HTML::Spelling::Site Template Test::HTML::Recursive::DeprecatedTags Test::TrailingSpace
    - gem install sass compass compass-blueprint
    - sudo -H `which python3` -m pip install pycotap vnu_validator
script: "m() { SKIP_SPELL_CHECK=1 make \"$@\" ; } ; cd vim-begin/tt2-source/ && bash -x bin/install-npm-deps.sh && ./gen-helpers && m && m test"
