#!/usr/bin/env bash

_finder()
{
    ( find src -name '*.html.tt2' | (LC_ALL=C sort) )
}

(
echo "SRC_TT2S = $(_finder | perl -lpe 's/$/ \\/')"
echo
echo "DEST_HTMLS = $(_finder | perl -lpe 's/\.tt2//; s{^src/}{dest/}' | perl -lpe 's/$/ \\/' )"
echo
) > lib/make/include.mak

echo "include lib/make/main.mak" > Makefile
