#!/bin/bash

_finder()
{
    ( find src -name '*.html.tt2' | (LC_ALL=C sort) )
}

(
echo "SRC_TT2S = $(_finder | perl -lape 's/$/ \\/')"
echo
echo "DEST_HTMLS = $(_finder | perl -lape 's/\.tt2//; s{^src/}{dest/}'| perl -lape 's/$/ \\/')"
echo
) > include.mak
